### PR TITLE
Fix #137 Failed to clear cache

### LINKED ISSUE #137: Failed to clear OPCache
I get "Failed to clear OPCache for file /home/vladimir/sites/b2batwork/app/cache/dev/translations/catalogue.en.1cd7e874b24ab41081c7781e4161053bf515fc91.php (500 Internal Server Error)" in v2.1.3 I think error is that you deleting cache files before invalidation (Translation/Translator.php 117).
 See http://php.net/manual/en/function.opcache-invalidate.php#116372

### PR DESCRIPTION
**Pull request by alinalexandru**

### CODE REVIEW

**Comment by alinalexandru** [comment]
Fixes #137

**Comment by alinalexandru** [comment]
Could you please review this PR?
I don't think the errors are caused by my code

**Comment by ThatCheck** [comment]
The error is always present. I have update today from master I have the error, again :) !

**Comment by ThatCheck** [comment]
And I have found the solution, by default php de-activate the opcache in cli (by the opcache.enable_cli set to 0), I make a pr request.

**Pull request merged**
