### PR TITLE
Always set file, also for new key

### PR DESCRIPTION
**Pull request by allartk**
When using the profile data for adding new keys, after adding a translation, the file_id will be null. This pull is an attempt to set it to a best guess value base on domain transUnit and format param.

### CODE REVIEW

**Comment by acrobat** [comment]
We also hit this bug, without the file_id we can't export our translations. @cedric-g is possible to have a look at this fix and merge if this is correct? Thanks!

**Comment by acrobat** [comment]
We also hit this bug, without the file_id we can't export our translations. @cedric-g is possible to have a look at this fix and merge if this is correct? Thanks! 

/cc @sdieunidou

**Comment by sdieunidou** [comment]
@allartk we have fixed tests on master, can you rebase your pull request please ?

**Comment by sdieunidou** [comment]
Fixed with #284

**Pull request closed without merging**
