### PR TITLE
:bug: Fix render twig in controller for overriding purpose

### PR DESCRIPTION
**Pull request by bricejulia**

### CODE REVIEW

**Comment by pmontoya** [comment]
👍

**Comment by ankhzet** [comment]
@bricejulia, please, resolve conflicts in pull request.
Without this fix it's almost impossible to override bundle's templates in Symfony 3.4 (I can't figure other way than overriding actions in controller) >_<.

Also, it would fix #323

**Comment by noniagriconomie** [comment]
@spike31 any news for this one? Thank you

**Comment by DanieleGBX** [comment]
I do realize how annoying this might be, but this PR is solving some critical bugs that are making using this bundle impossible. @spike31 would it be possible to merge this and release it?

**Comment by ankhzet** [comment]
Thank you!

**Pull request merged**
