### PR TITLE
Symfony 4 support

### PR DESCRIPTION
**Pull request by Bukashk0zzz**
😢

### CODE REVIEW

**Comment by eugenekurasov** [comment]
👍  - now need fix tests and PR done )

**Comment by eugenekurasov** [comment]
@spike31 can you merge this PR?)
Closes:
#294

**Comment by Bukashk0zzz** [comment]
🥂😎

**Comment by spike31** [comment]
Good job! 
I will merge and create a tag next week.

**Comment by rodmarzavala** [comment]
Thanks for your time && work guys!

**Comment by jlemale** [comment]
Nice work guys !
But I just noticed the export command is missing

**Comment by eugenekurasov** [comment]
Hi, 
@jlemale can you Create issue and put notice message?

**Comment by jlemale** [comment]
@eugenekurasov Hi, I've just created one : https://github.com/lexik/LexikTranslationBundle/issues/306

**Pull request merged**
