### PR TITLE
[fix] TranslationStorageDefinition

### PR DESCRIPTION
**Pull request by denya-vs**

### CODE REVIEW

**Comment by pawelkolanowski** [comment]
@denya-vs It's work for you? After installing got error: `Too few arguments to function Lexik\Bundle\TranslationBundle\Storage\AbstractDoctrineStorage::__construct(), 0 passed in /_PATH_/var/cache/dev/appDevDebugProjectContainer.php on line 2414 and exactly 3 expected in /_PATH_/vendor/lexik/translation-bundle/Storage/AbstractDoctrineStorage.php:34`

**Comment by denya-vs** [comment]
yes it`s work if you checkout to last dev-master 9ae3d76800ee5dc26a42f412e28d404103fcf4d7
and apply my changes.
Exception _Too few arguments to function_  already fixed in dev-master

**Comment by pawelkolanowski** [comment]
`$ composer info` shows: `lexik/translation-bundle             dev-patch-1 b59f6d9`
And the composer.json file contains:
```
    "repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:denya-vs/LexikTranslationBundle.git"
        }
    ],
    "require": {
        "lexik/translation-bundle": "dev-patch-1"
    },
```

I'm still getting an error `Too few arguments`.

**Comment by denya-vs** [comment]
```
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/denya-vs/LexikTranslationBundle"
        }
    ],
"lexik/translation-bundle": "dev-master#c57c5547f66cd9516809874e0b2ddc1f7bcc4dea",
```

**Comment by acassan** [comment]
Fix by this one: 

```
$className = sprintf('lexik_translation.%s.translation_storage.class', $storage);
$storageDefinition->setArguments($args);
$storageDefinition->setClass('%'.$className.'%');
```

Missing this line on your build: 
`$storageDefinition->setArguments($args);`

**Comment by acassan** [comment]
Workaround with compiler pass
Override wrong definition in container.

>`/**
 * Class LexikTranslationPass
 */
class LexikTranslationPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container)
    {
    	$storage = StorageInterface::STORAGE_ORM;
    	
		$args[] = array(
			'trans_unit'  => new Parameter(sprintf('lexik_translation.%s.trans_unit.class', $storage)),
			'translation' => new Parameter(sprintf('lexik_translation.%s.translation.class', $storage)),
			'file'        => new Parameter(sprintf('lexik_translation.%s.file.class', $storage)),
		);
		
		$storageDefinition = new Definition();
		$className = sprintf('lexik_translation.%s.translation_storage.class', $storage);
		$storageDefinition->setArguments($args);
		$storageDefinition->setClass('%'.$className.'%');
	
		$container->setDefinition('lexik_translation.translation_storage', $storageDefinition);
    }
}`

Just define your storage class at the beginning of function.

**Comment by NVasse** [comment]
Any merge planned with the fix provided by @acassan ?

**Comment by sdieunidou** [comment]
See #272

**Pull request closed without merging**
