### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by HecFranco**

### CODE REVIEW

**Comment by bartmcleod** [comment]
@HecFranco this seems to be the same PR as the earlier one? And it should be made against master. The 6.0 branch is to be used when your changes are specific to that version. Lastest and greatest should be targeting master.

**Comment by HecFranco** [comment]
@bartmcleod I have already changed the source branch.

**Comment by bartmcleod** [comment]
@HecFranco I wonder why no checks are run, maybe I need to reconfigure something... Also would need to know it it actually works with SF 7.

**Comment by k0d3r1s** [comment]
this is last library blocking my upgrade to 7.0. any updates here? need any help?

**Comment by bartmcleod** [comment]
@k0d3r1s We can fix this, probably.

**Comment by bartmcleod** [comment]
This PR is incomplete. It will not allow to "require" the package, because you only added sf 7 under "require-dev". Also, in sf -7 I see a lot of additional dependencies, that are not installed with this bundle, and should have been installed, so more dependencies will need to be added.

**Comment by bartmcleod** [comment]
While I now have a branch on my repo that supports installation with Sf 7, it fails to load the translations in the browser due to a javascript error.

**Comment by bartmcleod** [comment]
I close this, because a lot more had to be done, the UI also had bugs, possibly introduced by using a new angular version (that must be it). It is also possible bug reports exist for those, I will have a look if so and if they can be closed. In any case, I will create a new PR for SF 7 and probably merge that. It is possible that the UI fixes must be backported to the 6 branch.

**Pull request closed without merging**
