### PR TITLE
Updated translator definition according to SF 3.3 changes

### LINKED ISSUE #258: Translator changed in symfony3.3
From https://github.com/symfony/symfony/blob/master/UPGRADE-3.3.md

The Symfony\Bundle\FrameworkBundle\Translation\Translator constructor now takes the default locale as 3rd argument. Not passing it will trigger an error in 4.0.

As the Lexik Translator object is configured with extra values, i get a "Array expected, got Object" or "Array expected, got String" on the last argument passed in the container configuration  
<argument type="service" id="session" on-invalid="ignore" />

Just adding the default locale does not seem to work properly in a local config.xml, after changing it i don't get a service error anymore but the translations are no longer appearing on the screen.

### PR DESCRIPTION
**Pull request by cedric-g**
Fix #258

### CODE REVIEW

**Comment by GregHubs** [comment]
I've tried, but got this error : 
Fatal error: Cannot declare class AppKernel, because the name is already in use in C:\...\vendor\lexik\translation-bundle\Tests\app\AppKernel.php on line 102

**Comment by raziel057** [comment]
@cedric-g works for me too, thanks

**Comment by cedric-g** [comment]
Thx for the feed back :) but I want to test again with 3.2 before merge it (I need to fin some time).

**Comment by klausbreyer** [comment]
After using lexik under your commit and upgrading to symfony 3.3  I receive the following migration, when I do a migration diff: 

```
/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20170619141603 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE influencer_basic ADD ass LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json_array)\'');
        $this->addSql('ALTER TABLE lexik_translation_file CHANGE domain domain VARCHAR(191) NOT NULL, CHANGE locale locale VARCHAR(191) NOT NULL, CHANGE extention extention VARCHAR(191) NOT NULL, CHANGE path path VARCHAR(191) NOT NULL, CHANGE hash hash VARCHAR(191) NOT NULL');
        $this->addSql('ALTER TABLE lexik_trans_unit_translations CHANGE locale locale VARCHAR(191) NOT NULL');
        $this->addSql('ALTER TABLE lexik_trans_unit CHANGE key_name key_name VARCHAR(191) NOT NULL, CHANGE domain domain VARCHAR(191) NOT NULL');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE influencer_basic DROP ass');
        $this->addSql('ALTER TABLE lexik_trans_unit CHANGE key_name key_name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, CHANGE domain domain VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE lexik_trans_unit_translations CHANGE locale locale VARCHAR(10) NOT NULL COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE lexik_translation_file CHANGE domain domain VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, CHANGE locale locale VARCHAR(10) NOT NULL COLLATE utf8_unicode_ci, CHANGE extention extention VARCHAR(10) NOT NULL COLLATE utf8_unicode_ci, CHANGE path path VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, CHANGE hash hash VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci');
    }
}
```

Why has the length of the fields changed?

**Comment by pesseyjulien** [comment]
Any update on this issue ?

**Comment by edgartebar** [comment]
Any update on this PR?

**Comment by ioweb-gr** [comment]
Hi, this one seems to work OK for me on symfony 3.3.4 too.

**Comment by nicodmf** [comment]
For me no, i removed the line https://github.com/lexik/LexikTranslationBundle/pull/260/files#diff-1c64574ff1f633f0df3aac6fa7a25c7bR56 for bundle works. Symfony v3.3.4 with mongo

**Comment by lordjancso** [comment]
@cedric-g when will you tag a new release?

**Comment by lordjancso** [comment]
@cedric-g seriously... what do you suggest?

**Comment by drewek-smf** [comment]
@cedric-g Is this project still maintained? We are currently stuck on Symfony 3.2 just because of this lib not supporting 3.3, and apparently fixes are not going into new releases... If I need to switch to another translation lib, I just want to know early.

**Pull request merged**
