### PR TITLE
changed isMasterRequest to isMainRequest due to deprecation in Symfon…

### PR DESCRIPTION
**Pull request by sebo32**
…y 5.3

### CODE REVIEW

**Comment by bartmcleod** [comment]
@sebo32 I guess we should first create a 5.2 branch and then merge this into master

**Comment by sebo32** [comment]
That would be great.
Feel free to choose appropriate target branch for the request.

**Comment by raziel057** [comment]
@bartmcleod Could you create a 5.2 branch to apply this accept this PR on master after?

**Comment by bartmcleod** [comment]
@raziel057 I created a 5.2 branch

**Comment by raziel057** [comment]
Thanks that's fine

**Pull request merged**
