### PR TITLE
Rest and DataGrid implementation added to get messages based on Symfon 2.7 Profiler token

### PR DESCRIPTION
**Pull request by Rvanlaak**
Rest and DataGrid implementation added to get messages based on Symfon 2.7 Profiler token

### CODE REVIEW

**Comment by cedric-g** [comment]
Thx, I will try to do the Angular side next week :smiley:

**Comment by Rvanlaak** [comment]
What about adding some extra features, shall I add some extra "views" on the Symfony-side?

Like "missing translations", maybe also add a "domain translation completion percentage"?

**Comment by cedric-g** [comment]
Why not, and maybe this "domain translation completion percentage" page could be a full Symfony page as the create form.

**Comment by Rvanlaak** [comment]
I'd propose to make that page the 'index' action of the Bundle.

I've also written a cookbook article about calling a command in a controller, so it might also be an idea to make the import/export command accessible (?) 

http://symfony.com/doc/current/cookbook/console/command_in_controller.html

**Comment by Rvanlaak** [comment]
The available filters could be identical to those that will be available in 2.8

https://github.com/symfony/symfony/commit/65f92916a2046c86c928dcc7c626b8447f066315

**Comment by cedric-g** [comment]
I think it's better to keep the grid as main page as it's the main purpose, but maybe we will have to re-orgamize the view. And some people use the bundle in production env so some features that rely on profiler data won't be available.

**Comment by Rvanlaak** [comment]
@cedric-g any idea when you're able to work on the grid? :+1:

**Comment by cedric-g** [comment]
I started to work on it, but need to find some time to finish it.

**Comment by cedric-g** [comment]
@Rvanlaak I've pushed some changes on the angular side, I added a select to choose a profile token or "all translation" (only the 10 latest token for GET method are shown).

**Comment by Rvanlaak** [comment]
:+1: will test it later today. Why ony GET requests? POST requests can also make use of the translator right? I'd like to be able to manually enter a token otherwise :wink:

**Comment by Rvanlaak** [comment]
The feature already works well, but think the UX could be a little bit better :+1: 

* Because we have 6 languages, the edit button falls of the screen. Maybe add a small edit icon while hovering over the translatable value, and also add 'Save all' / 'Cancel all' buttons at the bottom of the page?
* The dropdown select with the keys looks okay, maybe put it right of the 'empty cache' button and add the URL of the request? Translators probably won't get it otherwise.
* The search filters do not seem to work after a token is selected.

**Comment by cedric-g** [comment]
I used a dropdown because it was the easy way for me to switch the translation "source", but this not final. The search fitlers do not work if we select a token because the action does not handle them.

I also wonder if a checkbox to automatically create untranslated keys that does not exist in DB would be convenient or not.

**Comment by Rvanlaak** [comment]
> I also wonder if a checkbox to automatically create untranslated keys that does not exist in DB would be convenient or not.

Think that should be a configuration option, right? Or do you mean the scenario where an English translation of a key is available, but that key is not available in the French translation? 

Weblate does gather all these features under ["monolingual components"](https://docs.weblate.org/en/latest/admin/projects.html#monolingual-components).

**Comment by cedric-g** [comment]
Yes it can be an option, the scenario is the profiler find a key that does not exist in the DB, so a key that  has never been imported (for any reason). I just wonder if it would be convenient to add the key in the database (instead of skip it) to allow users to edit it.

**Comment by Rvanlaak** [comment]
:+1:  on adding it to the database (by default), even if a fallback is used. That would allow us to spot missing translations by opening the PROD translation grid once in a while. 

I think you always should translate a key, right? This would also keep the structure of the keys in the `.yml` files in sync (after dumping to files) if a developer forgot to add the key in one language.

**Comment by cedric-g** [comment]
I've updated the branch, I've added 2 new options:

```yml
# app/config/config.yml
lexik_translation:
    dev_tools:
        enable: true
        create_missing: true
```
`dev_tools.enable`: set to true to enable features based on the profiler, basically I check this option instead of checking the SF env == dev.
`dev_tools.create_missing`: if true, while getting missing translations from a profile, if a key/domain pair does not exist in DB the bundle will create it instead of skip it (it will make the translation appear in the grid and allow users to translate it).

So if `dev_tools.enable` is true we can also add the "domain translation completion percentage" page, do you want to do this page ?
I will try to find a better way to display the save button and make the pagination and filters work properly when the grid list some translations from a profile.

**Comment by Rvanlaak** [comment]
Will it also work if `dev_tools.enable` is `false` and `dev_tools.create_missing` is `true`? That probably will be the setting for PROD environments?

**Comment by cedric-g** [comment]
No both options need to be `true`. It add missing translations from a profile, so the profiler has to be injected in the `DataGridRequestHandler` (and I inject the profiler if `dev_tools.enable` is `true`).

**Comment by Rvanlaak** [comment]
The new header with the data source options is working great! Some things I'm missing, please let me know if it would be better to create separate issues of it:

* message (or other feedback) that there are no translations when a certain profile is selected
* when `all` is selected, the profiles aren't hidden
* maybe add the new header features next to the header and 'add translation' button? looks like there is enough space left over there
* we have seven languages, so working with the checkboxes for the columns start to become a bit hard
* empty cache button could be moved next to the `Add translation` button

Will make a PR with a start of an overview page within the hour :+1:

**Comment by cedric-g** [comment]
> message (or other feedback) that there are no translations when a certain profile is selected

Yes, it would be better than just an empty grid :smile: 

> when all is selected, the profiles aren't hidden

I'm aware of this, but I don't understand why it's not hidden as the show/hide state of these elements rely on js variable.

> maybe add the new header features next to the header and 'add translation' button? looks like there is enough space left over there

> empty cache button could be moved next to the Add translation button

The header and the 'add translation' button are not in the angular template, so if we move the profiles selector and the empty cache button in this part of the page we will have to consider the whole page as the angular template.

**Comment by Rvanlaak** [comment]
I've summarized everything in issue https://github.com/lexik/LexikTranslationBundle/issues/165 so the PRs can be referenced to that.

**Comment by Rvanlaak** [comment]
The `create_missing` setting doesn't seem to work properly. The `translation units` seem to be created, but the actual translation isn't saved. Noticed this after emptying the database and doing some pageviews. There also aren't created any `translation file` entries, so will this work in the export command?

**Pull request merged**
