### PR TITLE
Support 7

### PR DESCRIPTION
**Pull request by bartmcleod**
- Supports only SF 7
- Fixes UI issues that were probably introduced with using the newer Angular version, or changes in a dependency. Http responses are now promises and must be handled as such. A couple of fixes were needed, this might introduce new UI bugs, but from what I could test manually I think it is looking good and working.

### CODE REVIEW

**Comment by bartmcleod** [comment]
@k0d3r1s  Yes, splitting that would be the "normal" procedure. I am not even sure the bug was introduced by the new Angular version. On second thought, I am pretty sure I tested that to work just fine, but it is quite some time ago and a cached script version may have been observed at the time: I cannot be sure anymore. What I need to do now is just make it work and everything that needs to be done to make it work will be in the same PR. This PR is also not complete. Although the UI and the commands all seem to work just fine, the unit tests fail, because Propel does not support Symfony 7. So I'm currently updating this to remove all Propel related code.

**Comment by k0d3r1s** [comment]
@bartmcleod hey, do you have any ETA here?

**Comment by gilles-g** [comment]
@bartmcleod 
I'm ok too to remove Propel, and maybe one day why not mongo.

**Comment by bartmcleod** [comment]
@k0d3r1s I have some time for it today. I am stuck at the unit tests: a new XmlFileDriver is in use that does not accept the old settings, but also gives no suggestions on what correct settings could be.

**Comment by Seb33300** [comment]
You should create separate pull request to fix UI issues and Symfony upgrade if they are unrelated.
This will make the review easier and will allow maintainers to merge them faster.

**Comment by k0d3r1s** [comment]
@bartmcleod hey, any updates here?

**Comment by bartmcleod** [comment]
@k0d3r1s I have looked at it several times, but I can't understand how the underlying component is failing. I mean I understand the original component is no longer there, and I only assumed that the one I'm using now would be the correct replaced, but it obviously isn't and I can't find documentation on what would be the correct replacement.

**Comment by bartmcleod** [comment]
@k0d3r1s I managed to fix the unit tests on my machine. Now I need to figure out why the build still fails on GitHub.

**Comment by bartmcleod** [comment]
@k0d3r1s The build fails because it somehow uses node 16 actions and GitHub has evolved to use node 20 actions. So nothing to do with the code itself, but I need to fix the action before the build will pass

**Comment by bartmcleod** [comment]
Now that I have passing tests I will merge it, because I tested the UI and commands already when the code itself was fixed. This means that SF 6 users will have to target the 6.0 branch instead of master from now on.

**Pull request merged**
